owner: "letaw"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/pon_filt"
type: "unrestricted"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  pon_filt:
    description: "Filtering of a VCF based on a panel of normals, as created by KDL panel_of_normals tool."
    include:
      - pon_filt.xml
      - pon_filt.py
