owner: "letaw"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/remove_zero_dp"
type: "unrestricted"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  remove_zero_dp:
    description: "Remove VCF entries that contain DP=0 in the SAMPLE field."
    include:
      - remove_zero_dp.xml
      - remove_zero_dp.py
