owner: "onwuzu"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/vcf_merge"
type: "unrestricted"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  vcf_merge:
    description: "Merge VCFs produced by various variant callers."
    include:
      - vcf_merge.xml
      - vcf_merge.py
