owner: "onwuzu"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/variant_metrics_umi"
type: "unrestricted"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  bkgd_metrics:
    description: "Metrics calculated at the variant level to estimate background allele frequencies."
    include:
      - bkgd_metrics.xml
      - bkgd_metrics.py
      - doc_tools.py
      - vcf_tools.py
