owner: "letaw"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/cgd_tx_eff_old"
type: "unrestricted"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  cgd_tx_eff:
    description: "Apply annotations from Annovar to a VCF."
    include:
      - cgd_tx_eff_old.xml
      - cgd_tx_eff_old.py
