owner: "campbena"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/homozygosity"
homepage_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/homozygosity"
categories:
  - "KDL Tools"
repositories:
  annovar:
    description: "Functionally annotates genetic variants"
    include:
      - annovar.xml

