categories: 
  - "CompBio Galaxy Wrappers"
description: "Estimate cell type abundance from a mixed population given gene expression data."
homepage_url: "https://github.com/ohsu-comp-bio/cibersort"
name: cibersort
owner: creason
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/cibersort"
