owner: "letaw"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/htseq_count"
homepage_url: "https://github.com/htseq/htseq"
type: "unrestricted"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  htseq_count:
    description: "Count aligned reads in a BAM file that overlap features in a GFF file."
    include:
      - htseq-count.xml
      - tool_data_table_conf.xml.sample
      - tool-data/*
