name: "bwa_mem2"
owner: "onwuzu"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/bwa-mem2"
homepage_url: "https://github.com/bwa-mem2/bwa-mem2"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  bwa_mem2:
    description: "Map low-divergent sequences against a large reference genome."
    include:
      - bwa_mem2.xml
      - tool-data/*
      - tool_data_table_conf.xml.sample
