owner: "letaw"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/gatk4_auto"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  gatk4_auto_collectreadcounts:
    description: "Collects read counts at specified intervals."
    include:
      - gatk4_auto_collectreadcounts.xml
      - macros.xml
      - tool-data/*
      - tool_data_table_conf.xml.sample
 gatk4_auto_applybqsr:
    description: "Apply base quality score recalibration."
    include:
      - macros.xml
      - gatk4_auto_applybqsr.xml
      - tool_data_table_conf.xml.sample
      - all_fasta.loc.sample
  gatk4_auto_baserecalibrator:
    description: "Generates recalibration table for Base Quality Score Recalibration (BQSR)."
    include:
      - macros.xml
      - gatk4_auto_baserecalibrator.xml
      - tool_data_table_conf.xml.sample
      - all_fasta.loc.sample
  gatk4_auto_countbases:
    description: "Count bases in a SAM/BAM/CRAM file"
    include:
      - macros.xml
      - gatk4_auto_countbases.xml
      - tool_data_table_conf.xml.sample
      - all_fasta.loc.sample
  gatk4_auto_markduplicates:
    description: "Identifies duplicate reads"
    include:
      - macros.xml
      - gatk4_auto_markduplicates.xml
      - tool_data_table_conf.xml.sample
      - all_fasta.loc.sample
  gatk4_auto_sortvcf:
    description: "Sorts one or more VCF files"
    include:
      - macros.xml
      - gatk4_auto_sortvcf.xml
      - tool_data_table_conf.xml.sample
      - all_fasta.loc.sample
  gatk4_auto_splitcigarreads:
    description: "Split Reads with N in Cigar"
    include:
      - macros.xml
      - gatk4_auto_splitncigarreads.xml
      - tool_data_table_conf.xml.sample
      - all_fasta.loc.sample
