owner: "onwuzu"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/fgbio"
homepage_url: "http://fulcrumgenomics.github.io/fgbio/"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  fgbio_fastq_to_bam:
    description: "Generates an unmapped BAM (or SAM or CRAM) file from fastq files."
    include:
      - macros.xml
      - fgbio_fastq_to_bam.xml
  fgbio_call_molocular_consensus_reads:
    description: "Calls consensus sequences from reads with the same unique molecular tag."
    include:
      - macros.xml
      - fgbio_call_molocular_consensus_reads.xml
  fgbio_group_reads_by_umi:
    description: "Groups reads together that appear to have come from the same original molecule."
    include:
      - macros.xml
      - fgbio_group_reads_by_umi.xml
  fgbio_sort_bam:
    description: "Sorts a SAM or BAM file."
    include:
      - macros.xml
      - fgbio_sort_bam.xml
  fgbio_sort_fastq:
    description: "Sorts a FASTQ file."
    include:
      - macros.xml
      - fgbio_sort_fastq.xml
  fgbio_trim_fastq:
    description: "Trims reads in one or more line-matched fastq files to a specific read length."
    include:
      - macros.xml
      - fgbio_trim_fastq.xml

