owner: "letaw"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/kallisto"
homepage_url: "https://pachterlab.github.io/kallisto/"
categories:
  - "KDL Tools"
repositories:
  kallisto_quant:
    description: "quantifying abundances of transcripts from bulk and single-cell RNA Seq data"
    include:
      - kallisto_quant.xml
      - macros.xml
      - tool_data_table_conf.xml.sample
      - tool_data_table_conf.xml.test
      - test-data/*
      - tool-data/*
