owner: "pleyte"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/cgd_tx_eff"
type: "unrestricted"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  cgd_tx_eff:
    description: "Apply annotations from Annovar and HGVS/UTA to a VCF."
    include:
      - cgd_tx_eff.xml
      - src/*
      - test-data/*
