owner: "pleyte"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/cgd_tx_eff"
type: "unrestricted"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  tfx_cgd:
    description: "Update a VCF with transcript-effects and nomenclature from Annovar and HGVS."
    include:
      - tfx_cgd.xml
      - src/**
      - test-data/*
  tfx_cgd_comparison:
    description: "Create comparison of Transcript Effects and CGD data export"
    include:
      - tfx_cgd_comparison.xml
      - src/**
      - test-data/test_export_in.csv
      - test-data/test_comparison_in.vcf
  