owner: "pleyte"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/cgd_tx_eff"
type: "unrestricted"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  tfx_cgd:
    description: "Update a VCF with transcript-effects and nomenclature from Annovar and HGVS."
    include:
      - tfx_cgd.xml
      - src/**
      - test-data/*
      - tool_data_table_conf.xml.sample
      - tool-data/*