owner: "letaw"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/dsp_runner"
homepage_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/dsp_runner"
type: "unrestricted"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  dsp_runner:
    description: "NanoString DSP RUV-III Normalization"
    include:
      - dsp_runner.xml
      - dsp_runner.R
      - dsp_inputs.R
      - evaluation.R
      - helpers.R
      - normalization.R
      - plots.R
      - summarization.R
      - qc_check.R