owner: "onwuzu"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/vcf_tools"
type: "unrestricted"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  vcf_merge_2:
    description: "Merge multiple VCFs."
    include:
      - vcf_merge.py
      - vcf_merge.xml
  vcf_filter_2:
    description: "Filter VCF based on FILTER column."
    include:
      - vcf_filter.py
      - vcf_filter.xml
