owner: "onwuzu"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/vcf"
type: "unrestricted"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  var_label:
    description: "Label variants in a VCF."
    include:
      - var_label.py
      - var_label.xml
  var_select:
    description: "Select variants in a VCF."
    include:
      - var_select.py
      - var_select.xml
  vcf_merge:
    description: "Merge multiple VCFs."
      include:
        - vcf_merge.py
        - vcf_merge.xml
  vcf_select:
    description: "Select VCF fields."
      include:
        - vcf_select.py
        - vcf_select.xml
