owner: "campbena"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/file_count"
homepage_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/file_count"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  file_count:
    description: "For a particular directory, count the number of files, and compare to an input value."
    include:
      - file_count.xml
      - file_count.py
