owner: "chongbe"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/fusion_illustrator"
homepage_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/fusion_illustrator"
type: "unrestricted"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  fusion_illustrator:
    description: "KMT2A-PTD illustration"
    include:
      - fusion_illustrator.R
      - fusion_illustrator.xml
  fusiontranscript_illustrator:
    description: "Fusion transcript illustration"
    include:
      - ensembl_func.R
      - fusiontranscript_illustrator.R
      - fusiontranscript_illustrator.xml