owner: "letaw"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/bedtools"
homepage_url: "https://github.com/arq5x/bedtools2"
type: "unrestricted"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  bedtools_bamtofastq:
    description: "Convert from BAM to FastQ."
    include:
      - bamToFastq.xml
      - macros.xml
      - tool_data_table_conf.xml.sample
      - tool-data/*
