owner: "campbena"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/homozygosity"
homepage_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/homozygosity"
categories:
  - "KDL Tools"
repositories:
  homozygosity:
    description: "Finds runs of homozygosity."
    include:
      - gtrellis_homozygosity.R
      - homozygosity.sh
      - homozygosity.xml
      - zygosity_runs.py
