owner: "campbena"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/homozygosity"
homepage_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/homozygosity"
categories:
  - "KDL Tools"
repositories:
  gtrellis_homozygosity:
    description: "Provide plot reflecting runs of homozygosity."
    include:
      - gtrellis_homozygosity.R
      - gtrellis_homozygosity.xml
  zygosity_runs:
    description: "Finds runs of homozygosity, provide text output describing runs."
    include:
      - zygosity_runs.py
      - zygosity_runs.xml
