owner: "campbena"
remote_repository_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/split_mult_alleles_vcf"
homepage_url: "https://github.com/ohsu-comp-bio/compbio-galaxy-wrappers/tree/master/split_mult_alleles_vcf"
categories:
  - "CompBio Galaxy Wrappers"
repositories:
  split_mult_alleles_vcf:
    description: "Where multiple alleles are listed by commas in a VCF, make each a seperate entry."
    include:
      - split_mult_alleles_vcf.py
      - split_mult_alleles_vcf.xml
